### ISSUE TITLE
Blank Page after successful install

### ISSUE THREAD

**Issue by ZoKK** [eschnou/storytlr#24]
hi. I installed storytlr on www.zoharkiaav.co.za and all I see is a blank page after the install success page. Can anyone help?

**Comment by eschnou** [comment]
Most likely a PHP error due to a missing extension. Can you check your php logs for an error message ?You can also set debug=1 in protected/config/config.ini to see if you get any error message displayed.

**Comment by ZoKK** [comment]
hi there. thanks for responding. I have set debug=1 in protected/config/config.ini yet still there are no messages displayed.

This is what I get from the error_log File:

[17-Oct-2010 07:20:32] PHP Fatal error:  Uncaught exception 'Zend_Config_Exception' with message 'Error parsing /home/ahdevili/public_html/zoharkiaav.co.za/protected/config/config.ini on line 8
' in /home/ahdevili/public_html/zoharkiaav.co.za/protected/library/Zend/Config/Ini.php:181
Stack trace:
#0 /home/ahdevili/public_html/zoharkiaav.co.za/protected/library/Zend/Config/Ini.php(201): Zend_Config_Ini->_parseIniFile('/home/ahdevili/...')
#1 /home/ahdevili/public_html/zoharkiaav.co.za/protected/library/Zend/Config/Ini.php(125): Zend_Config_Ini->_loadIniFile('/home/ahdevili/...')
#2 /home/ahdevili/public_html/zoharkiaav.co.za/protected/application/Bootstrap.php(152): Zend_Config_Ini->__construct('/home/ahdevili/...', 'general')
#3 /home/ahdevili/public_html/zoharkiaav.co.za/protected/application/Bootstrap.php(92): Bootstrap::setupConfiguration()
#4 /home/ahdevili/public_html/zoharkiaav.co.za/protected/application/Bootstrap.php(80): Bootstrap::prepare()
#5 /home/ahdevili/public_html/zoharkiaav.co.za/index.php(48): Bootstrap::run()
#6 {main}
  thrown in /home/ahdevili/public_html/zoharkiaav.co.za/protected/library/Zend/Config/Ini.php on line 181

**Comment by eschnou** [comment]
It seems you have an error in your config.ini file (zoharkiaav.co.za/protected/config/config.ini on line 8). Maybe due to a strange character in there ? Sometimes using special characters in your MySQL password can be the cause.

**Comment by ZoKK** [comment]
that line indicates the database name which is made up of alpha-numeric characters only... the database password is also made up of alpha-numeric characters

However there is an underscore in the database name. Could that be a problem?
