### ISSUE TITLE
Cannot upload photos after install

### ISSUE THREAD

**Issue by dapen** [eschnou/storytlr#49]
Getting this error while trying to upload a photo.

From the webpage
Ooops

Hmmm.... something just went wrong. The error has been logged and our code monkeys will look into it as soon as they are back from their daily walk in the park.

From the applicationException.log file

2011-09-14T05:56:58+02:00 DEBUG (7): Exception for request http://domainXXXX.com//admin/post/submit
Unknown or unsupported file type (application/octet-stream)
#0 /home/X/public_html/domainXXXX/protected/application/admin/controllers/PostController.php(373): Files->fitWidth('6', 240, 'small')
#1 /home/X/public_html/domainXXXX/protected/application/admin/controllers/PostController.php(341): Admin_PostController->newItem(Array)
#2 /home/X/public_html/domainXXXX/protected/library/Zend/Controller/Action.php(513): Admin_PostController->submitAction()
#3 /home/X/public_html/domainXXXX/protected/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('submitAction')
#4 /home/X/public_html/domainXXXX/protected/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 /home/X/public_html/domainXXXX/protected/application/Bootstrap.php(82): Zend_Controller_Front->dispatch()
#6 /home/X/public_html/domainXXXX/index.php(48): Bootstrap::run()
#7 {main}

**Comment by jmhobbs** [comment]
What's the file type and extension of the photo?

**Comment by dapen** [comment]
.jpg
